---
# tasks file for myapache

- name: "Checking httpd installed or not" 
  command: "rpm -q httpd"
  register: web
  ignore_errors: yes 

- name: "Installing Httpd"
  package:
        name: "httpd" 
        state: present
  when: web.rc !=0 
     
- name: "Checking php installed or not"
  command: "rpm -q php"       
  register: php
  ignore_errors: yes

- name: "Installing php.."
  package: 
        name: php
        state: present
  when: php.rc !=0      

- name: "copying php code"
  copy: 
        src: index.php
        dest: /var/www/html/index.php  
         
- name: "Starting Httpd services.."
  service: 
     name: "httpd"
     state: started
     enabled: yes

     #- name: "Configuring firewall"
     # command: "systemctl stop firewalld" 
           
  
    
